// packages/preact-blurhash-as/src/Hello.tsx
/* @jsx h */
import { h, VNode } from 'preact';

export interface HelloProps {
  greeting: string;
}

export default function Hello({ greeting }: HelloProps): VNode {
  if (process.env.NODE_ENV !== 'production') {
    console.log('This code would not appear on production builds');
  }
  return <h1>{`Hello ${greeting}`}</h1>;
}

// packages/vue-blurhash-as/src/Hello.tsx
/** @jsx h */
import { h, defineComponent, toRefs } from 'vue';

export default defineComponent({
  name: 'Hello',
  props: {
    greeting: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const { greeting } = toRefs(props);

    return () => {
      if (process.env.NODE_ENV !== 'production') {
        console.log('This code would not appear on production builds');
      }

      return <h1>Hello {greeting.value}</h1>;
    };
  },
});
