// packages/solid-blurhash-as/src/BlurhashStaticImagePlaceholder.tsx
import { JSX } from 'solid-js';
import { BlurhashStaticOptions } from './types';
import { CSS_PLACEHOLDER } from './utils';

export interface BlurhashStaticImagePlaceholderProps extends BlurhashStaticOptions {
  visible: boolean;
  placeholder: string;
}

export default function BlurhashStaticImagePlaceholder(
  props: BlurhashStaticImagePlaceholderProps,
): JSX.Element {
  return (
    <img
      src={props.placeholder}
      alt="Blurhash Placeholder"
      class="blurhash-as__placeholder"
      style={{
        ...CSS_PLACEHOLDER,
        opacity: props.visible ? 1 : 0,
      }}
      onLoad={props.onLoad}
    />
  );
}

// packages/preact-blurhash-as/src/BlurhashStaticImagePlaceholder.tsx
/** @jsx h */
import { h } from 'preact';
import { BlurhashStaticOptions } from './types';
import { CSS_PLACEHOLDER } from './utils';

export interface BlurhashStaticImagePlaceholderProps extends BlurhashStaticOptions {
  visible: boolean;
  placeholder: string;
}

export default function BlurhashStaticImagePlaceholder(
  {
    visible,
    onLoad,
    placeholder,
  }: BlurhashStaticImagePlaceholderProps,
): JSX.Element {
  return (
    <img
      src={placeholder}
      alt="Blurhash Placeholder"
      className="blurhash-as__placeholder"
      style={{
        ...CSS_PLACEHOLDER,
        opacity: visible ? 1 : 0,
      }}
      onLoad={onLoad}
    />
  );
}
