// packages/solid-blurhash-as/src/BlurhashStaticContainer.tsx
import { createSignal, JSX } from 'solid-js';
import useLaze from 'solid-laze';
import {
  getAspectRatioBoxStyle,
  ASPECT_RATIO_CONTENT,
  IMAGE_CONTAINER,
  IMAGE,
  getEmptyImageURL,
  shimStyle,
} from './utils';

export interface BlurhashStaticContainerProps {
  src: string;
  alt: string;
  width: number;
  height: number;
  onLoad?: () => void;
  children: (visible: () => boolean, onLoad: () => void) => JSX.Element;
}

export default function BlurhashStaticContainer(
  props: BlurhashStaticContainerProps,
): JSX.Element {
  const [showPlaceholder, setShowPlaceholder] = createSignal(true);
  const laze = useLaze<HTMLDivElement>();
  const [defer, setDefer] = createSignal(true);

  function onPlaceholderLoad() {
    setDefer(false);
  }

  return (
    <div
      ref={laze.ref}
      class="blurhash-as__aspect-ratio-box"
      style={getAspectRatioBoxStyle({ width: props.width, height: props.height })}
    >
      <div
        class="blurhash-as__aspect-ratio-content"
        style={ASPECT_RATIO_CONTENT}
      >
        <div
          class="blurhash-as__image-container"
          style={IMAGE_CONTAINER}
        >
          {
            laze.visible && (
              <img
                class="blurhash-as__image"
                src={defer() ? getEmptyImageURL({ width: props.width, height: props.height }) : props.src}
                alt={props.alt}
                onLoad={() => {
                  if (!defer()) {
                    setShowPlaceholder(false);
                    props.onLoad?.();
                  }
                }}
                style={shimStyle({
                  ...IMAGE,
                  opacity: showPlaceholder() ? 0 : 1,
                })}
              />
            )
          }
          {props.children(showPlaceholder, onPlaceholderLoad)}
        </div>
      </div>
    </div>
  );
}

// packages/react/src/BlurhashStaticContainer.tsx
import type { JSX } from 'react';
import { useState } from 'react';
import useLaze from 'react-laze';
import {
  ASPECT_RATIO_CONTENT,
  IMAGE,
  IMAGE_CONTAINER,
  getAspectRatioBoxStyle,
  getEmptyImageURL,
} from './utils';

export interface BlurhashStaticContainerProps {
  src: string;
  alt: string;
  width: number;
  height: number;
  onLoad?: () => void;
  children: (visible: boolean, onLoad: () => void) => JSX.Element;
}

export function BlurhashStaticContainer({
  src,
  alt,
  width,
  height,
  children,
  onLoad,
}: BlurhashStaticContainerProps): JSX.Element {
  const [showPlaceholder, setShowPlaceholder] = useState(true);
  const { ref, visible } = useLaze<HTMLDivElement>();
  const [defer, setDefer] = useState(true);

  function onPlaceholderLoad() {
    setDefer(false);
  }

  return (
    <div
      ref={ref}
      className="blurhash-as__aspect-ratio-box"
      style={getAspectRatioBoxStyle({ width, height })}
    >
      <div
        className="blurhash-as__aspect-ratio-content"
        style={ASPECT_RATIO_CONTENT}
      >
        <div className="blurhash-as__image-container" style={IMAGE_CONTAINER}>
          {visible && (
            <img
              className="blurhash-as__image"
              src={defer ? getEmptyImageURL({ width, height }) : src}
              alt={alt}
              onLoad={() => {
                if (!defer) {
                  setShowPlaceholder(false);
                  onLoad?.();
                }
              }}
              style={{
                ...IMAGE,
                opacity: showPlaceholder ? 0 : 1,
              }}
            />
          )}
          {children(showPlaceholder, onPlaceholderLoad)}
        </div>
      </div>
    </div>
  );
}
