// packages/solid/src/BlurhashCSSPlaceholder.tsx
import { createEffect, JSX } from 'solid-js';
import { BlurhashOptions } from './types';
import useBlurhashCSS from './useBlurhashCSS';
import { CSS_PLACEHOLDER, shimStyle } from './utils';

export interface BlurhashCSSPlaceholderProps extends BlurhashOptions {
  blur?: string;
  scale?: number;
  visible: boolean;
}

export default function BlurhashCSSPlaceholder(
  props: BlurhashCSSPlaceholderProps,
): JSX.Element {
  const result = useBlurhashCSS(props);

  createEffect(() => {
    if (result()) {
      props.onLoad?.();
    }
  });

  return (
    <div
      class="blurhash-as__placeholder"
      style={shimStyle({
        ...CSS_PLACEHOLDER,
        ...result(),
        filter: `blur(${props.blur ?? '20px'})`,
        transform: `scale(${props.scale ?? '1.2'})`,
        opacity: props.visible ? 1 : 0,
      })}
    />
  );
}

// packages/react-blurhash-as/src/BlurhashCSSPlaceholder.tsx
import React, { useEffect } from 'react';
import { BlurhashOptions } from './types';
import useBlurhashCSS from './useBlurhashCSS';
import { CSS_PLACEHOLDER } from './utils';

export interface BlurhashCSSPlaceholderProps extends BlurhashOptions {
  filter?: string;
  scale?: number;
  visible: boolean;
}

export default function BlurhashCSSPlaceholder(
  {
    visible,
    filter,
    scale,
    onLoad,
    ...props
  }: BlurhashCSSPlaceholderProps,
): JSX.Element {
  const result = useBlurhashCSS(props);

  useEffect(() => {
    onLoad?.();
  }, [onLoad, result]);

  return (
    <div
      className="blurhash-as__placeholder"
      style={{
        ...CSS_PLACEHOLDER,
        ...result,
        filter: `blur(${filter ?? '20px'})`,
        transform: `scale(${scale ?? '1.2'})`,
        opacity: visible ? '1' : '0',
      }}
    />
  );
}
