// packages/solid-blurhash-as/src/BlurhashStaticImagePlaceholder.tsx
import { JSX } from 'solid-js';
import { BlurhashStaticOptions } from './types';
import { CSS_PLACEHOLDER } from './utils';

export interface BlurhashStaticImagePlaceholderProps extends BlurhashStaticOptions {
  visible: boolean;
  placeholder: string;
}

export default function BlurhashStaticImagePlaceholder(
  props: BlurhashStaticImagePlaceholderProps,
): JSX.Element {
  return (
    <img
      src={props.placeholder}
      alt="Blurhash Placeholder"
      class="blurhash-as__placeholder"
      style={{
        ...CSS_PLACEHOLDER,
        opacity: props.visible ? 1 : 0,
      }}
      onLoad={props.onLoad}
    />
  );
}

// packages/react-blurhash-as/src/BlurhashStaticImagePlaceholder.tsx
import React from 'react';
import { BlurhashStaticOptions } from './types';
import { CSS_PLACEHOLDER } from './utils';

export interface BlurhashStaticImagePlaceholderProps extends BlurhashStaticOptions {
  visible: boolean;
  src: string;
}

export default function BlurhashStaticImagePlaceholder(
  {
    visible,
    onLoad,
    src,
  }: BlurhashStaticImagePlaceholderProps,
): JSX.Element {
  return (
    <img
      src={src}
      alt="Blurhash Placeholder"
      className="blurhash-as__placeholder"
      style={{
        ...CSS_PLACEHOLDER,
        opacity: visible ? 1 : 0,
      }}
      onLoad={onLoad}
    />
  );
}
