// packages/react/src/BlurhashBoundary.tsx
import type { JSX, ReactNode } from 'react';
import { Suspense } from 'react';
import { getEmptyImageURL } from './utils';

export interface BlurhashBoundaryProps {
  width: number;
  height: number;
  children?: ReactNode;
}

export function BlurhashEmpty(props: BlurhashBoundaryProps): JSX.Element {
  return (
    <img
      src={getEmptyImageURL(props)}
      alt="Blurhash Placeholder"
      className="blurhash-as__placeholder"
    />
  );
}

export function BlurhashBoundary({
  width,
  height,
  children,
}: BlurhashBoundaryProps): JSX.Element {
  return (
    <Suspense fallback={<BlurhashEmpty width={width} height={height} />}>
      {children}
    </Suspense>
  );
}

// packages/solid/src/BlurhashBoundary.tsx
import { Suspense, JSX } from 'solid-js';
import { getEmptyImageURL } from './utils';

export interface BlurhashBoundaryBaseProps {
  width: number;
  height: number;
}

export function BlurhashEmpty(props: BlurhashBoundaryBaseProps): JSX.Element {
  return (
    <img
      src={getEmptyImageURL(props)}
      alt="Blurhash Placeholder"
      class="blurhash-as__placeholder"
    />
  );
}

export interface BlurhashBoundaryProps extends BlurhashBoundaryBaseProps {
  children: JSX.Element;
}

export function BlurhashBoundary(props: BlurhashBoundaryProps): JSX.Element {
  return (
    <Suspense fallback={<BlurhashEmpty width={props.width} height={props.height} />}>
      {props.children}
    </Suspense>
  );
}

export default BlurhashBoundary;
